# Generated by Django 2.0.5 on 2018-11-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181102_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='rest_id',
            field=models.ForeignKey(default=1007, on_delete=django.db.models.deletion.CASCADE, to='orders.Restaurant'),
        ),
    ]
