# Generated by Django 2.1.3 on 2018-11-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181103_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('total', models.IntegerField(default=0)),
                ('cust_id', models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='orders.Customer')),
                ('rest_id', models.ForeignKey(default=1007, on_delete=django.db.models.deletion.CASCADE, to='orders.Restaurant')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantities',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rest_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Item'),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Bill'),
        ),
    ]
