# Generated by Django 2.0.5 on 2018-11-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feed_back',
            field=models.CharField(max_length=255),
        ),
    ]
