# Generated by Django 2.1.7 on 2019-03-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190323_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_add_restaurant', 'Can add restaurant'),)},
        ),
    ]
