# Generated by Django 2.1.7 on 2019-03-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190323_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'permissions': (('can_add_restaurant', 'Can add restaurant'),)},
        ),
    ]
