# Generated by Django 2.1.7 on 2019-03-24 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20190324_0328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_add_restaurant', 'Can add restaurant'),)},
        ),
    ]
