# Generated by Django 2.1.7 on 2019-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20190324_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('userid', models.IntegerField(default=1007, primary_key=True, serialize=False)),
                ('can_add_restaurant', models.IntegerField(default=0)),
            ],
        ),
    ]
