# Generated by Django 2.1.7 on 2019-03-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AddField(
            model_name='manager',
            name='permissions',
            field=models.PositiveSmallIntegerField(choices=[(1, 'no_add'), (2, 'add_edit'), (3, 'add_edit_delete')], default=1),
        ),
    ]
