# Generated by Django 2.1.7 on 2019-03-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20190328_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='permissions',
            field=models.PositiveSmallIntegerField(choices=[(1, 'regular'), (2, 'premium'), (3, 'gold')], default=1),
        ),
        migrations.AlterField(
            model_name='manager',
            name='permissions',
            field=models.PositiveSmallIntegerField(choices=[(1, 'add'), (2, 'add_edit'), (3, 'add_edit_delete')], default=1),
        ),
    ]
